language: node_js
node_js:
  - 12.16.2
cache: npm

script: 
  - echo "skipping tests"

deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: react-editor-app

notifications:
  slack: codetolearnworkspace:HOCdD1zlJ0ViIqE5Bt2Df7Nm